theme: askclass-home-theme
title: "Awana Vietnam"
description: >
  Welcome to Awana Vietnam!

ach:
  date_format: "%b %d, %y"
  short_name: "Awana Vietnam"
  color:
    theme: "#2A9D8F"
    bg: "#264653"
  url: "https://awanavietnam.com"
  categories:
    - education
  logo:
    image: "logo.svg"
    size: 240
    alt_image: "logo-icon.svg"
    alt_size: 70
    sizes: [ 48, 96, 144, 192, 300, 512, 1024 ]
  meta:
    apple_icon: "logo-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      edtech,
      education,
      technology,
      learning,
      teaching,
      student,
      educator,
      university
  social:
    twitter: awanavietnam
  font_families:
    - Lora
    - Open+Sans:ital,wght@0,300;0,400;0,500;0,700;1,400;1,700
    - Josefin+Sans
    - Share+Tech+Mono
    - Lexend
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

collections_dir: content
collections:
  modules:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "modules"
    values:
      layout: "modules"

sass:
  style: compact

include:
  - index.html
  - 404.html
  - pwabuilder-sw.js
  - content

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - askclass-home-theme.gemspec
  - CNAME
  - runme.sh

